title: Kacper Korban's blog
email: kacper.f.korban@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kacper Korban's blog site
baseurl: ""
url: "https://kacperfkorban.github.io"
twitter_username: KacperKorban
github_username:  KacperFKorban

# Build settings
markdown: kramdown
theme: jekyll-simple-dark
plugins:
  - jekyll-feed
